# Generated by Django 6.0 on 2025-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
